### PR TITLE
Structure html de base + sass + mockups

### PR DESCRIPTION
**Pull request by myleneb**
- base des pages html
- sass + css
- dossiers avec les mockups

### CODE REVIEW

**Comment by RichardHitier** [comment]
Merci !

c'est visible ici:

http://richardhitier.github.io/aperincub/


j'ai plus qu'à bosser :-)

**Comment by RichardHitier** [comment]
au fait, avec quoi tu as généré cette arborescence ?


Le 21/03/2015 10:33, Mylène Bressan a écrit :
> - base des pages html
> - sass + css
> - dossiers avec les mockups
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/RichardHitier/aperincub/pull/1
> 
> -- Commit Summary --
> 
>   * Structure html de base + sass + mockups
> 
> -- File Changes --
> 
>     A assets/.sass-cache/195a914216cb4cba2ffd7761f06570e3804468d4/_hover-link.scssc (0)
>     A assets/.sass-cache/195a914216cb4cba2ffd7761f06570e3804468d4/_link-colors.scssc (0)
>     A assets/.sass-cache/195a914216cb4cba2ffd7761f06570e3804468d4/_unstyled-link.scssc (0)
>     A assets/.sass-cache/32d3980486d704c65bf6e745b7e7c47011ab07f9/_utilities.scssc (0)
>     A assets/.sass-cache/50f01acd1a57e4c48719259f84948af012eea1c4/_base.scssc (0)
>     A assets/.sass-cache/50f01acd1a57e4c48719259f84948af012eea1c4/_sprite-img.scssc (0)
>     A assets/.sass-cache/51c09cf21bc49049f74b73b9a519a804419da45a/_color.scssc (0)
>     A assets/.sass-cache/51c09cf21bc49049f74b73b9a519a804419da45a/_general.scssc (0)
>     A assets/.sass-cache/51c09cf21bc49049f74b73b9a519a804419da45a/_sprites.scssc (0)
>     A assets/.sass-cache/51c09cf21bc49049f74b73b9a519a804419da45a/_tables.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_animation.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_appearance.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_background-clip.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_background-origin.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_background-size.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_border-radius.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_box-shadow.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_box-sizing.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_columns.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_deprecated-support.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_filter.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_flexbox.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_font-face.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_hyphenation.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_images.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_inline-block.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_opacity.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_regions.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_text-shadow.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_transform.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_transition.scssc (0)
>     A assets/.sass-cache/5b08b770eb42fe9f1db90654f9d7472546829e72/_user-interface.scssc (0)
>     A assets/.sass-cache/6240c5975250c41807fc39d4abd7c22bfaec3974/_index.sassc (0)
>     A assets/.sass-cache/6c3cc1f7fffa9f6a810680fa13879962e3c572de/_clearfix.scssc (0)
>     A assets/.sass-cache/6c3cc1f7fffa9f6a810680fa13879962e3c572de/_float.scssc (0)
>     A assets/.sass-cache/6c3cc1f7fffa9f6a810680fa13879962e3c572de/_hacks.scssc (0)
>     A assets/.sass-cache/6c3cc1f7fffa9f6a810680fa13879962e3c572de/_min.scssc (0)
>     A assets/.sass-cache/6c3cc1f7fffa9f6a810680fa13879962e3c572de/_reset.scssc (0)
>     A assets/.sass-cache/6c3cc1f7fffa9f6a810680fa13879962e3c572de/_tag-cloud.scssc (0)
>     A assets/.sass-cache/769203038fc2381db4adb289a32ff644ebe60ea8/_bullets.scssc (0)
>     A assets/.sass-cache/769203038fc2381db4adb289a32ff644ebe60ea8/_horizontal-list.scssc (0)
>     A assets/.sass-cache/769203038fc2381db4adb289a32ff644ebe60ea8/_inline-block-list.scssc (0)
>     A assets/.sass-cache/769203038fc2381db4adb289a32ff644ebe60ea8/_inline-list.scssc (0)
>     A assets/.sass-cache/785bed907c4ae260b740ee441a001dd7e04e71e2/_brightness.scssc (0)
>     A assets/.sass-cache/785bed907c4ae260b740ee441a001dd7e04e71e2/_contrast.scssc (0)
>     A assets/.sass-cache/806683a30f33e9adead5d7a9e587c6a7121afcdd/_alternating-rows-and-columns.scssc (0)
>     A assets/.sass-cache/806683a30f33e9adead5d7a9e587c6a7121afcdd/_borders.scssc (0)
>     A assets/.sass-cache/806683a30f33e9adead5d7a9e587c6a7121afcdd/_scaffolding.scssc (0)
>     A assets/.sass-cache/8342ec71cdff08d4e7850c7f8368fef56ee9199c/_grid-background.scssc (0)
>     A assets/.sass-cache/85472b63f2569dec74cd4901974ee09dc7048f28/_links.scssc (0)
>     A assets/.sass-cache/85472b63f2569dec74cd4901974ee09dc7048f28/_lists.scssc (0)
>     A assets/.sass-cache/85472b63f2569dec74cd4901974ee09dc7048f28/_text.scssc (0)
>     A assets/.sass-cache/85472b63f2569dec74cd4901974ee09dc7048f28/_units.scssc (0)
>     A assets/.sass-cache/85472b63f2569dec74cd4901974ee09dc7048f28/_vertical_rhythm.scssc (0)
>     A assets/.sass-cache/957eb5b03d82309975cdae0c05a4db6cf685a301/ie.sassc (0)
>     A assets/.sass-cache/957eb5b03d82309975cdae0c05a4db6cf685a301/ie.scssc (0)
>     A assets/.sass-cache/957eb5b03d82309975cdae0c05a4db6cf685a301/main.sassc (0)
>     A assets/.sass-cache/957eb5b03d82309975cdae0c05a4db6cf685a301/print.sassc (0)
>     A assets/.sass-cache/957eb5b03d82309975cdae0c05a4db6cf685a301/print.scssc (0)
>     A assets/.sass-cache/957eb5b03d82309975cdae0c05a4db6cf685a301/screen.scssc (0)
>     A assets/.sass-cache/abe9245783409fa596d2b09ccc6400fee1dc833f/ie.sassc (0)
>     A assets/.sass-cache/abe9245783409fa596d2b09ccc6400fee1dc833f/main.sassc (0)
>     A assets/.sass-cache/abe9245783409fa596d2b09ccc6400fee1dc833f/print.sassc (0)
>     A assets/.sass-cache/ae6e14058252885610c598cc6b6296abbb42dda4/_var.sassc (0)
>     A assets/.sass-cache/bc92100f8e653a3de4e8cb150f38f828dca3cd0e/_compass.scssc (0)
>     A assets/.sass-cache/dada9f600fd57ea8907820a522c3bc9e825975e4/_ellipsis.scssc (0)
>     A assets/.sass-cache/dada9f600fd57ea8907820a522c3bc9e825975e4/_force-wrap.scssc (0)
>     A assets/.sass-cache/dada9f600fd57ea8907820a522c3bc9e825975e4/_nowrap.scssc (0)
>     A assets/.sass-cache/dada9f600fd57ea8907820a522c3bc9e825975e4/_replacement.scssc (0)
>     A assets/.sass-cache/df7d2a053ecd84eecf38d1e6b2d08bdf8b60d2c8/_css3.scssc (0)
>     A assets/.sass-cache/df7d2a053ecd84eecf38d1e6b2d08bdf8b60d2c8/_reset.scssc (0)
>     A assets/.sass-cache/df7d2a053ecd84eecf38d1e6b2d08bdf8b60d2c8/_support.scssc (0)
>     A assets/.sass-cache/df7d2a053ecd84eecf38d1e6b2d08bdf8b60d2c8/_typography.scssc (0)
>     A assets/.sass-cache/df7d2a053ecd84eecf38d1e6b2d08bdf8b60d2c8/_utilities.scssc (0)


>     A assets/.sass-cache/e2137aa504f6b9d56740885c9e256d255851ddd3/_fonts.sassc (0)
>     A assets/.sass-cache/e2137aa504f6b9d56740885c9e256d255851ddd3/_grid.sassc (0)
>     A assets/.sass-cache/e2137aa504f6b9d56740885c9e256d255851ddd3/_no-js.sassc (0)
>     A assets/.sass-cache/e2137aa504f6b9d56740885c9e256d255851ddd3/_typo.sassc (0)
>     A assets/.sass-cache/e2137aa504f6b9d56740885c9e256d255851ddd3/_var.sassc (0)
>     A assets/.sass-cache/e5d403031502da215019eacc7b1683497f6e09c4/_footer.sassc (0)
>     A assets/.sass-cache/e5d403031502da215019eacc7b1683497f6e09c4/_header.sassc (0)
>     A assets/.sass-cache/e5d403031502da215019eacc7b1683497f6e09c4/_menu-top.sassc (0)
>     A assets/.sass-cache/e5d403031502da215019eacc7b1683497f6e09c4/_responsive.sassc (0)
>     A assets/.sass-cache/e5d403031502da215019eacc7b1683497f6e09c4/_section.sassc (0)
>     A assets/.sass-cache/e5d403031502da215019eacc7b1683497f6e09c4/_site-boxed.sassc (0)
>     A assets/.sass-cache/f4e0375db71eee4e7c63cce2a9c590795257319a/_buttons.sassc (0)
>     A assets/config.rb (23)
>     A assets/css/ie.css (1)
>     A assets/css/main.css (417)
>     A assets/css/print.css (1)
>     A assets/fonts/DroidSans/DroidSans-Bold.ttf (0)
>     A assets/fonts/DroidSans/DroidSans.ttf (0)
>     A assets/fonts/Montserrat/Montserrat-Bold.ttf (0)
>     A assets/fonts/Montserrat/Montserrat-Regular.ttf (0)
>     A assets/fonts/Montserrat/OFL.txt (92)
>     A assets/fonts/icons/flaticon.css (67)
>     A assets/fonts/icons/flaticon.eot (0)
>     A assets/fonts/icons/flaticon.html (305)
>     A assets/fonts/icons/flaticon.svg (3)
>     A assets/fonts/icons/flaticon.ttf (0)
>     A assets/fonts/icons/flaticon.woff (0)
>     A assets/fonts/icons/license.pdf (0)
>     A assets/img/arrow-bottom.svg (29)
>     A assets/img/arrow-top.svg (16)
>     A assets/img/ico.png (0)
>     A assets/js/html5.js (8)
>     A assets/sass/base/_fonts.sass (93)
>     A assets/sass/base/_form.sass (0)
>     A assets/sass/base/_grid.sass (50)
>     A assets/sass/base/_mixins.sass (0)
>     A assets/sass/base/_no-js.sass (0)
>     A assets/sass/base/_typo.sass (79)
>     A assets/sass/base/_var.sass (41)
>     A assets/sass/composants/_buttons.sass (23)
>     A assets/sass/composants/_form.sass (126)
>     A assets/sass/ie.sass (5)
>     A assets/sass/layout/_footer.sass (26)
>     A assets/sass/layout/_header.sass (0)
>     A assets/sass/layout/_menu-top.sass (44)
>     A assets/sass/layout/_responsive.sass (36)
>     A assets/sass/layout/_section.sass (159)
>     A assets/sass/layout/_site-boxed.sass (12)
>     A assets/sass/main.sass (21)
>     A assets/sass/pages/_index.sass (42)
>     A assets/sass/pages/_localisation.sass (0)
>     A assets/sass/print.sass (3)
>     M index.html (111)
>     A localisation.html (34)
>     A mockups/mockup_idee.bmml (539)
>     A mockups/mockup_idee.jpg (0)
>     A participants.html (37)
>     A projets.html (37)
> 
> -- Patch Links --
> 
> https://github.com/RichardHitier/aperincub/pull/1.patch
> https://github.com/RichardHitier/aperincub/pull/1.diff
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/RichardHitier/aperincub/pull/1
> 


-- 
Richard Hitier
06 44 26 75 82
http://www.co-libri.org/

**Comment by myleneb** [comment]
Le 22/03/2015 18:22, Richard Hitier a écrit :
> au fait, avec quoi tu as généré cette arborescence ?
>
>
avec mes mains?
elle est pas idéale je sais mais c'est ce que j'utilise pour travailler.
Organise-la différemment si tu veux, pas de souci!

**Comment by RichardHitier** [comment]
Le 22/03/2015 18:24, Mylène Bressan a écrit :
> 
> 
> Le 22/03/2015 18:22, Richard Hitier a écrit :
>> au fait, avec quoi tu as généré cette arborescence ?
>>
>>
> avec mes mains?
223 fichiers ?

non, ya des trucs qui sont pas de toi, et je pensais que tu avais
utilisé un générateur, ou un framework, ou je sais pas quoi.

> elle est pas idéale je sais mais c'est ce que j'utilise pour travailler.
> Organise-la différemment si tu veux, pas de souci!
ouh là :-)
il n'y a aucun jugement dans ma question.

c'était de la pure curiosité:
j'espère également apprendre à ton contact.





-- 
Richard Hitier
06 44 26 75 82
http://www.co-libri.org/

**Comment by myleneb** [comment]
Le 22/03/2015 18:31, Richard Hitier a écrit :
>
> 223 fichiers ?
>
> non, ya des trucs qui sont pas de toi, et je pensais que tu avais
> utilisé un générateur, ou un framework, ou je sais pas quoi.
>
oh oui en effet! le cache sass! dsl j'ai pas fait attention quand j'ai
add le dossier sass
il est généré par compass
http://compass-style.org/

**Comment by RichardHitier** [comment]
Le 22/03/2015 18:33, Mylène Bressan a écrit :
> 
> 
> il est généré par compass
> http://compass-style.org/
> 
> 
ah, ok, faudra que tu me montres un de ces jours.


-- 
Richard Hitier
06 44 26 75 82
http://www.co-libri.org/

**Pull request merged**
